= View navigation in Vaadin Designer 1.2

In this tutorial you will learn how to set up event listeners to handle user input, and leverage those event listeners to build navigation between views. The views are created by using the new responsive templates in Vaadin Designer 1.2. This tutorial assumes you have Vaadin Designer 1.2.x installed for Eclipse or IntelliJ IDEA. The code samples in this tutorial are written using Java 8. Let’s get started.

== Create designs
At first you need some views. Let's create the application's main layout and views.

* Create your application's main layout design using the template called `AppShell` and name it `MainLayoutDesign`.
* Create two other designs using the template called `Tiles`. Name the designs `DashboardViewDesign` and `ReportsViewDesign` respectively.
* Create a design called `CustomizeViewDesign` using the template called `formTemplate`.
* Finally, create a design called `AdminViewDesign` using the template called `CRUDTemplate`.

== Set application main layout
Start by creating a new class `MainLayout` extending `MainLayoutDesign`. The extended class is not modified at this point, but let's have it ready in advance.

Next set `MainLayout` as the content of your UI.

[source,java]
----
@Theme("mytheme")
public class MyUI extends UI {

    @Override
    protected void init(VaadinRequest vaadinRequest) {
        MainLayout layout = new MainLayout();
        setContent(layout);
    }

    @WebServlet(urlPatterns = "/*", name = "MyUIServlet", asyncSupported = true)
    @VaadinServletConfiguration(ui = MyUI.class, productionMode = false)
    public static class MyUIServlet extends VaadinServlet {
    }
}
----

== Create views from designs
To create a proper navigation you should use a `com.vaadin.ui.Navigator`. The Navigator uses URL fragments for selecting the active view and because of that the back button and linking to a view with a URL works.

Create four view classes implementing `com.vaadin.navigator.View`. Each view should extend one of your view designs. Extend `DashboardViewDesign`, `ReportsViewDesign`, `CustomizeViewDesign`, and `AdminViewDesign`. Name the extended classes `DashboardView`, `ReportsView`, `CustomizeView`, and `AdminView` respectively. The Navigator uses String view names to identify the views, so to make your life easier later, add a public view name field to each of the views.

[source,java]
----
public class DashboardView extends DashboardViewDesign implements View {
    public static final String VIEW_NAME = "dashboard";

    @Override
    public void enter(ViewChangeEvent event) {

    }
}
----

== Setup Navigator

Now your views are ready to be used with a Navigator. You need to create a Navigator and attach it to your UI with a designated area to the views called ViewDisplay. The MainLayout has a layout called `content` which is perfect for displaying the views. Modify UI init by adding constructing of Navigator.

[source,java]
----
@Override
protected void init(VaadinRequest vaadinRequest) {
    MainLayout layout = new MainLayout();
    setContent(layout);
    Navigator navigator = new Navigator(this, layout.content);
}
----

Add all your views to the navigator. And navigate to the DashboardView in UI init.

[source,java]
----
protected void init(VaadinRequest vaadinRequest) {
    MainLayout layout = new MainLayout();
    setContent(layout);
    Navigator navigator = new Navigator(this, layout.content);
    navigator.addView(DashboardView.VIEW_NAME, DashboardView.class);
    navigator.addView(ReportsView.VIEW_NAME, ReportsView.class);
    navigator.addView(CustomizeView.VIEW_NAME, CustomizeView.class);
    navigator.addView(AdminView.VIEW_NAME, AdminView.class);
    if (navigator.getState().isEmpty()) {
        navigator.navigateTo(DashboardView.VIEW_NAME);
    }
}
----

If your run the application at this point, the application URL fragment should be `#!dashboard` and you should see the dashboard view. You can already navigate using fragments, but let's add button click handling of the menu items next.

== Handle menu button clicks

Button click listeners are added in the MainLayout. Add a click listener for each of the menu action buttons and call `Navigator.navigateTo()` with the given view name. I have wrapped the navigateTo call in a private method doNavigate.

[source,java]
----
public MainLayout() {
    dashboard.addClickListener(event -> doNavigate(DashboardView.VIEW_NAME));
    reports.addClickListener(event -> doNavigate(ReportsView.VIEW_NAME));
    customize.addClickListener(event -> doNavigate(CustomizeView.VIEW_NAME));
    admin.addClickListener(event -> doNavigate(AdminView.VIEW_NAME));
}

private void doNavigate(String viewName) {
    UI.getCurrent().getNavigator().navigateTo(viewName);
}
----

Now the navigation is done properly and you can test it out. Clicking any of the menu items navigates to the correct view.
